version: "3.9"

services:
  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - mysqlapp-net
    environment:
      MYSQL_DATABASE: filesystem_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: my-secret-pw
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  app:
    build: .
    #    restart: always
    ports:
      - "8080:8080"
    networks:
      - mysqlapp-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/filesystem_db
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - .m2:/root/.m2

networks:
  mysqlapp-net:
